### ISSUE TITLE
[GraphQL Basics course] [Main Task] [Ramona]

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/playing-with-graphql#3]
Please start by reading the documentation, related to GraphQL: https://www.howtographql.com/
After reading each chapter - please briefly explain to me here what did you learn from it.
Format(example):

#### Chapter 1: Intro (https://graphql.org/learn/)
"It's covering the basics of graphql"
Questions: "How i can run it at my local PC"?

----

**Comment by atherdon** [comment]
@Ramona24 tell me if you have any questions

**Comment by atherdon** [comment]
can you tell me more about first lesson?

**Comment by atherdon** [comment]
@Ramona24 we're restarting our work on graphql server - tell me if you interested to join us

**Comment by Ramona24** [comment]
I apologize for not responding to this sooner, I thought I had. Thank you
very much for the opportunity but I am not able to work with your team at
this time.

**Comment by atherdon** [comment]
Sure, no problem
